### ISSUE TITLE
Build keeps failing with enet and system attribute errors

### ISSUE THREAD

**Issue by kih** [playingoDEERUX/growbrewproxy#85]
Build starts off failing and shows this
![image](https://user-images.githubusercontent.com/45693537/120072312-419b7580-c061-11eb-87bc-4f8c1fd7b0b3.png)

After reading previous issues I found this https://github.com/playingoDEERUX/growbrewproxy/issues/70#issuecomment-790354004, but doing whats in that reply just returns these errors
![image](https://user-images.githubusercontent.com/45693537/120072433-e61db780-c061-11eb-85e7-5a3e566881fb.png)

I reinstalled/updated enet using nuget and installed net 5.0, not sure why its erroring still

**Comment by majknez** [comment]
Remove the duplicates and try again

**Comment by kih** [comment]
> Remove the duplicates and try again

Doing that makes System.Management vanish, after readding it, the built .exe runs but it immediately gets an error

![image](https://user-images.githubusercontent.com/45693537/120072938-2847f880-c064-11eb-8fdb-ee5b21fc61af.png)

Reinstalling enet.managed from nuget does nothing

**Comment by majknez** [comment]
thats beacuse the enet folder path is expected somewhere else look the exception text and put the folders with binaries where growbrewproxy wants them to be

**Comment by kih** [comment]
Just did that, still keeps returning the same error

 ```
   ENet.Managed.ENetException: Failed to load ENet dynamic library. (Native last error: 0)
   at ENet.Managed.Internal.ThrowHelper.ThrowENetLibraryLoadFailed(Int32 lastError) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\ENet.Managed\Internal\ThrowHelper.cs:line 49
   at ENet.Managed.Platforms.Win32Platform.LoadDynamicLibrary(String dllPath) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\ENet.Managed\Platforms\Win32Platform.cs:line 53
   at ENet.Managed.Native.LibENet.LoadDllFromFile(String path) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\ENet.Managed\Native\LibENet.cs:line 393
   at ENet.Managed.Native.LibENet.LoadModuleFromFile(String path) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\ENet.Managed\Native\LibENet.cs:line 330
   at ENet.Managed.Native.LibENet.Load(String dllFile) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\ENet.Managed\Native\LibENet.cs:line 269
   at ENet.Managed.ManagedENet.Startup(ENetStartupOptions startupOptions) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\ENet.Managed\ManagedENet.cs:line 105
   at GrowbrewProxy.MainForm.MainForm_Load(Object sender, EventArgs e) in C:\Users\Admin\Desktop\growbrewproxy-master\GrowbrewProxy\MainForm.cs:line 712
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by kih** [comment]
Did you have to modify anything when you used this? If so, can you send the source you have that's working?

**Comment by Gorkido** [comment]
> > Remove the duplicates and try again
> 
> Doing that makes System.Management vanish, after readding it, the built .exe runs but it immediately gets an error
> 
> ![image](https://user-images.githubusercontent.com/45693537/120072938-2847f880-c064-11eb-8fdb-ee5b21fc61af.png)
> 
> Reinstalling enet.managed from nuget does nothing

Put enet.dll in the same directory as "GrowbrewProxy.exe".
